services:
  smart-calculator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:  
      - "3000:3000"
    container_name: smart-calculator
    networks:
      - smart-network
    restart: unless-stopped
  
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - smart-calculator
    networks:
      - smart-network
    restart: unless-stopped

networks:
  smart-network:
    driver: bridge